# Numpy 
* ref. an introduciton to Numpy and scipy

In [2]:
# import
import numpy
# import using alias
import numpy as np

## Array
* array
 * list와 유사하지만, array는 모든 원소들이 같은 형(type)이다. 보통 float 나 int형의 숫자 형을 사용함

In [3]:
a = np.array([1,4,5,8],float)
print a
print type(a)

[ 1.  4.  5.  8.]
<type 'numpy.ndarray'>


In [4]:
a[:2]

array([ 1.,  4.])

In [5]:
a[3]

8.0

In [6]:
a

array([ 1.,  4.,  5.,  8.])

In [7]:
# 배열은 다차원이 될수 있다.(multidimensional)
a = np.array([[1,2,3],[4,5,6]],float)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [8]:
a[0,0]

1.0

In [9]:
a[0,1]

2.0

In [10]:
a[1,:]

array([ 4.,  5.,  6.])

In [11]:
a[0,:]

array([ 1.,  2.,  3.])

In [12]:
a[:,2]

array([ 3.,  6.])

In [13]:
a[-1:,-2:]

array([[ 5.,  6.]])

In [14]:
# shape : size of each array dimension
a.shape

(2, 3)

In [15]:
# dtype : type of values
a.dtype

dtype('float64')

In [16]:
a = np.array([[1,2,3],[4,5,6]], float)
len(a)

2

In [17]:
2 in a

True

In [18]:
0 in a

False

In [19]:
# reshape
a = np.array(range(10),float)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [20]:
a = a.reshape((5,2))
a

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.]])

In [21]:
a.shape

(5, 2)

In [22]:
# copy : 새로운 객체를 생성 카피함
a = np.array([1,2,3],float)
b = a
c = a.copy()

In [23]:
print a,b,c

[ 1.  2.  3.] [ 1.  2.  3.] [ 1.  2.  3.]


In [24]:
a[0]=0
print a,b,c

[ 0.  2.  3.] [ 0.  2.  3.] [ 1.  2.  3.]


In [25]:
# c is another object, a,b has same reference.

In [26]:
# list
a.tolist()

[0.0, 2.0, 3.0]

In [27]:
list(a)

[0.0, 2.0, 3.0]

In [28]:
# tostring / fromstring
a = np.array([1,2,3],float)
s = a.tostring()
s

'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [29]:
print s

�?@@


In [30]:
np.fromstring(s)

array([ 1.,  2.,  3.])

In [31]:
# transpose (전치행렬)
a = np.array(range(6),float).reshape((2,3))
print a
print a.transpose()

[[ 0.  1.  2.]
 [ 3.  4.  5.]]
[[ 0.  3.]
 [ 1.  4.]
 [ 2.  5.]]


In [32]:
# flatten
a = np.array([[1,2,3],[4,5,6]],float)
print a
print a.flatten()

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
[ 1.  2.  3.  4.  5.  6.]


In [33]:
# concatenate
a = np.array([1,2],float)
b = np.array([3,4,5,6],float)
c = np.array([7,8,9],float)
np.concatenate((a,b,c))

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [34]:
a = np.array([[1,2],[3,4]],float)
b = np.array([[5,6],[7,8]],float)
np.concatenate((a,b))

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]])

In [35]:
np.concatenate((a,b),axis=0)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]])

In [36]:
np.concatenate((a,b),axis=1)

array([[ 1.,  2.,  5.,  6.],
       [ 3.,  4.,  7.,  8.]])

In [37]:
# newaxis
a = np.array([1,2,3],float)
a

array([ 1.,  2.,  3.])

In [38]:
a[:,np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.]])

In [39]:
a[:,np.newaxis].shape

(3, 1)

In [40]:
a[np.newaxis,:]

array([[ 1.,  2.,  3.]])

In [41]:
a[np.newaxis,:].shape

(1, 3)

# other way to create array


In [42]:
np.arange(5,dtype=float)

array([ 0.,  1.,  2.,  3.,  4.])

In [43]:
np.arange(1,6,2, dtype=int)
# from 1, to 6, step 2

array([1, 3, 5])

In [44]:
np.ones((2,3),dtype=float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [45]:
np.zeros(7,dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

In [46]:
a = np.array([[1,2,3],[4,5,6]], float)
np.zeros_like(a)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [47]:
np.ones_like(a)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [49]:
# identity matrix (단위행렬)
np.identity(4, dtype=float)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [50]:
# eye : k-th diagonal (대각행렬)
np.eye(4, k=1, dtype=float)

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

## array 수학

In [51]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)

In [52]:
a+b

array([ 6.,  4.,  9.])

In [53]:
a - b

array([-4.,  0., -3.])

In [54]:
a * b

array([  5.,   4.,  18.])

In [55]:
b / a

array([ 5.,  1.,  2.])

In [56]:
a % b

array([ 1.,  0.,  3.])

In [57]:
b ** a

array([   5.,    4.,  216.])

In [58]:
# 2 dimensional arrays
a = np.array([[1,2],[3,4]], float)
b = np.array([[2,0],[1,3]], float)
a * b

array([[  2.,   0.],
       [  3.,  12.]])

In [59]:
# error are thrown if arrays do not match in size.
a = np.array([1,2,3], float)
b = np.array([4,5], float)
a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [60]:
# broadcasting.
a = np.array([[1,2], [3,4], [5,6]], float)
b = np.array([-1,3], float)

In [61]:
a

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

In [62]:
b

array([-1.,  3.])

In [63]:
a + b

array([[ 0.,  5.],
       [ 2.,  7.],
       [ 4.,  9.]])

In [64]:
# b like
# array([[-1., 3.],
#        [-1., 3.],
#        [-1., 3.]])

In [65]:
# but. this is ambiguous. --> explictly we use newaxis

In [67]:
a = np.zeros((2,2), float)
b = np.array([-1,3], float)

In [68]:
print a
print b

[[ 0.  0.]
 [ 0.  0.]]
[-1.  3.]


In [69]:
a + b

array([[-1.,  3.],
       [-1.,  3.]])

In [70]:
a + b[np.newaxis,:]

array([[-1.,  3.],
       [-1.,  3.]])

In [71]:
b[np.newaxis,:]

array([[-1.,  3.]])

In [72]:
b[:,np.newaxis]

array([[-1.],
       [ 3.]])

In [73]:
a + b[:,np.newaxis]

array([[-1., -1.],
       [ 3.,  3.]])

In [75]:
# abs, sign, sqrt, log, log10, exp, sin, cos, tan, 
# arcsin, arccos, arctan, shinh, cosh, tanh, arcsinh, 
# arccosh, arctanh


In [76]:
a = np.array([1, 4, 9], float)

In [77]:
np.sqrt(a)

array([ 1.,  2.,  3.])

In [82]:
# floor, ceil, rint
# lower, upper, nearest(rounded)
a = np.array([1.1, 1.5, 1.9], float)

In [83]:
np.floor(a)

array([ 1.,  1.,  1.])

In [84]:
np.ceil(a)

array([ 2.,  2.,  2.])

In [85]:
np.rint(a)

array([ 1.,  2.,  2.])

In [86]:
# constant
print np.pi
print np.e

3.14159265359
2.71828182846


## array iteration

In [87]:
a = np.array([1,4,5], float)
for x in a:
    print x

1.0
4.0
5.0


In [88]:
a = np.array([[1,2], [3,4], [5,6]], float)
for x in a:
    print x

[ 1.  2.]
[ 3.  4.]
[ 5.  6.]


In [89]:
for (x,y) in a:
    print x*y

2.0
12.0
30.0


## basic array operations


In [90]:
a = np.array([2,4,3], float)
a.sum()

9.0

In [91]:
a.prod()

24.0

In [92]:
np.sum(a)

9.0

In [93]:
np.prod(a)

24.0

In [97]:
2*2+4*4+3*3

29

In [98]:
?np.prod

In [99]:
# mean, variance, std,...
a = np.array([2,1,9], float)

In [100]:
a.mean()

4.0

In [101]:
a.var()

12.666666666666666

In [102]:
a.std()

3.5590260840104371

In [103]:
a = np.array([2,1,9],float)

In [104]:
a.min()

1.0

In [105]:
a.max()

9.0

In [106]:
# argmin, argmax
a.argmin()

1

In [108]:
a.argmax()

2

In [109]:
# multidimentional matrix
a = np.array([[0,2],[3,-1],[3,5]],float)

In [110]:
a.mean(axis=0)

array([ 2.,  2.])

In [111]:
a.mean(axis=1)

array([ 1.,  1.,  4.])

In [115]:
print a.min(axis=0)
print a.max(axis=0)

[ 0. -1.]
[ 3.  5.]


In [117]:
print a.min(axis=1)
print a.max(axis=1)

[ 0. -1.  3.]
[ 2.  3.  5.]


In [118]:
# sorting
a = np.array([6,2,5,-1,0],float)
sorted(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]

In [119]:
a.sort()
a

array([-1.,  0.,  2.,  5.,  6.])

In [121]:
# clip
# = min(max(x,minval), maxval)
a = np.array([6,2,5,-1,0],float)
a.clip(0,5)

array([ 5.,  2.,  5.,  0.,  0.])

In [122]:
# unique
a = np.array([1,1,4,5,5,5,7], float)
np.unique(a)

array([ 1.,  4.,  5.,  7.])

In [123]:
# diagonal
a = np.array([[1,2], [3,4]], float)
print a

[[ 1.  2.]
 [ 3.  4.]]


In [124]:
a.diagonal()

array([ 1.,  4.])

## 비교 연산자와 값 테스팅

In [125]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)
a > b

array([ True, False, False], dtype=bool)

In [126]:
a == b

array([False,  True, False], dtype=bool)

In [127]:
a <=b 

array([False,  True,  True], dtype=bool)

In [128]:
c = a > b
c

array([ True, False, False], dtype=bool)

In [129]:
a = np.array([1, 3, 0], float)
a > 2

array([False,  True, False], dtype=bool)

In [130]:
c

array([ True, False, False], dtype=bool)

In [131]:
any(c)

True

In [132]:
all(c)

False

In [133]:
# and or not
a = np.array([1, 3, 0], float)

In [134]:
np.logical_and(a > 0, a < 3)

array([ True, False, False], dtype=bool)

In [135]:
b = np.array([True, False, False], dtype=bool)

In [136]:
np.logical_not(b)

array([False,  True,  True], dtype=bool)

In [137]:
c = np.array([False, True, False], dtype=bool)

In [138]:
np.logical_or(b,c)

array([ True,  True, False], dtype=bool)

In [139]:
# where(boolarray, truearray, falsearray)
a = np.array([1,3,0], float)
np.where(a != 0, 1 / a, a)

/Users/kobi78/pyvirenv/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: RuntimeWarning: divide by zero encountered in divide
  app.launch_new_instance()


array([ 1.        ,  0.33333333,  0.        ])

In [140]:
np.where(a > 0, 3, 2)

array([3, 3, 2])

In [141]:
# nonzero, NaN
a = np.array([[0,1], [3,0]], float)
a.nonzero()

(array([0, 1]), array([1, 0]))

In [142]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([  1.,  nan,  inf])

In [145]:
# NaN : Not a number, Inf : Infinite
np.isnan(a)

array([False,  True, False], dtype=bool)

In [146]:
np.isfinite(a)

array([ True, False, False], dtype=bool)

## 배열 원소 선택과 연산

In [148]:
a = np.array([[6, 4], [5, 9]], float)
a >= 6

array([[ True, False],
       [False,  True]], dtype=bool)

In [149]:
a [a >= 6]

array([ 6.,  9.])

In [150]:
sel = (a >= 6)
print sel
print a[sel]

[[ True False]
 [False  True]]
[ 6.  9.]


In [152]:
# using bool expression
a[np.logical_and(a > 5, a < 9)]

array([ 6.])

In [153]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)

In [154]:
a[b]

array([ 2.,  2.,  4.,  8.,  6.,  4.])

In [155]:
# 0th, 0th, 1st, 3rd, 2nd, 1st

In [156]:
a = np.array([2, 4, 6, 8], float)
a[[0, 0, 1, 3, 2, 1]]

array([ 2.,  2.,  4.,  8.,  6.,  4.])

In [158]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b, c]

array([  1.,   4.,  16.,  16.,   4.])

In [159]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a.take(b)

array([ 2.,  2.,  4.,  8.,  6.,  4.])

In [160]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([0, 0, 1], int)
a.take(b, axis=0)

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 2.,  3.]])

In [161]:
a.take(b, axis=1)

array([[ 0.,  0.,  1.],
       [ 2.,  2.,  3.]])

In [162]:
# put
a = np.array([0, 1, 2, 3, 4, 5], float)
b = np.array([9, 8, 7], float)

In [163]:
a.put([0,3], b)

In [164]:
a

array([ 9.,  1.,  2.,  8.,  4.,  5.])

In [165]:
a = np.array([0, 1, 2, 3, 4, 5], float)
a.put([0,3], 5)

In [166]:
a

array([ 5.,  1.,  2.,  5.,  4.,  5.])

## 벡터와 행렬 수학

In [167]:
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
np.dot(a,b)

5.0

In [168]:
# dot product
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4,0]], float)
a

array([[ 0.,  1.],
       [ 2.,  3.]])

In [169]:
np.dot(b,a)

array([  6.,  11.])

In [170]:
np.dot(a,b)

array([  3.,  13.])

In [171]:
np.dot(a,c)

array([[  4.,   0.],
       [ 14.,   2.]])

In [172]:
np.dot(c,a)

array([[ 2.,  4.],
       [ 0.,  4.]])

In [173]:
# inner , outer, cross product
a = np.array([1, 4, 0], float)
b = np.array([2, 2, 1], float)

In [174]:
np.outer(a,b)

array([[ 2.,  2.,  1.],
       [ 8.,  8.,  4.],
       [ 0.,  0.,  0.]])

In [175]:
np.inner(a, b)

10.0

In [176]:
np.cross(a, b)

array([ 4., -1., -6.])

In [177]:
# linear algebra calculation
# linalg
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float)
a

array([[ 4.,  2.,  0.],
       [ 9.,  3.,  7.],
       [ 1.,  2.,  1.]])

In [178]:
np.linalg.det(a)

-48.000000000000028

In [179]:
# eigenvectors of matrix
vals, vecs = np.linalg.eig(a)
print vals
print vecs

[ 8.85591316  1.9391628  -2.79507597]
[[-0.3663565  -0.54736745  0.25928158]
 [-0.88949768  0.5640176  -0.88091903]
 [-0.27308752  0.61828231  0.39592263]]


In [180]:
# inverse of matrix
b = np.linalg.inv(a)
b

array([[ 0.22916667,  0.04166667, -0.29166667],
       [ 0.04166667, -0.08333333,  0.58333333],
       [-0.3125    ,  0.125     ,  0.125     ]])

In [181]:
np.dot(a, b)

array([[  1.00000000e+00,   5.55111512e-17,   0.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   4.44089210e-16],
       [  0.00000000e+00,   1.38777878e-17,   1.00000000e+00]])

In [182]:
# singular value decomposition
a = np.array([[1, 3, 4], [5, 2, 3]], float)
U, s, Vh = np.linalg.svd(a)

In [183]:
U

array([[-0.6113829 , -0.79133492],
       [-0.79133492,  0.6113829 ]])

In [184]:
s

array([ 7.46791327,  2.86884495])

In [185]:
Vh

array([[-0.61169129, -0.45753324, -0.64536587],
       [ 0.78971838, -0.40129005, -0.46401635],
       [-0.046676  , -0.79349205,  0.60678804]])

## Polynomial mathematics(다항식 수학)

In [186]:
np.poly([-1, 1, 1, 10])

array([  1., -11.,   9.,  11., -10.])

반환 값은 다음에 대응하는 계수이다.
> $x^4-11x^3+9x^2+11x-10$

In [187]:
np.roots([1, 4, -2, 3])

array([-4.57974010+0.j        ,  0.28987005+0.75566815j,
        0.28987005-0.75566815j])

여기는 다음 식의 제곱근 한 것이다.
> $x^3+4x^2-2x+3$

In [188]:
# ... plyadd, polysub polymul, polydiv, .. polyval, polyfit

## Statistics

`mean`, `var`, `std`

In [190]:
a = np.array([1, 4, 3, 8, 9, 2, 3], float)
np.median(a) # 중앙값

3.0

In [191]:
# correlation coefficient 
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float)
c = np.corrcoef(a)

In [192]:
c

array([[ 1.        ,  0.72870505],
       [ 0.72870505,  1.        ]])

In [194]:
# covariance : 공분산
np.cov(a)

array([[ 0.91666667,  2.08333333],
       [ 2.08333333,  8.91666667]])

## Random numbers

In [195]:
np.random.seed(293423)

In [196]:
np.random.rand(5)

array([ 0.33677247,  0.52693437,  0.79529578,  0.78867702,  0.02147624])

In [197]:
np.random.rand(2,3)

array([[ 0.84612516,  0.0704939 ,  0.1526965 ],
       [ 0.77831701,  0.80821151,  0.82198398]])

In [198]:
np.random.rand(6).reshape(2,3)

array([[ 0.90239653,  0.8385685 ,  0.02638565],
       [ 0.33681448,  0.46480928,  0.61686496]])

In [199]:
np.random.random()

0.43767262538051455

In [201]:
np.random.randint(5,10) # randint(min, max)

6

In [202]:
# poisson distribution lambda=6.0
np.random.poisson(6.0)

5

In [203]:
# mean=1.5 , std=4.0
np.random.normal(1.5, 4.0)

-1.5224080889736675

In [204]:
# normal
np.random.normal()

0.957100788846741

In [206]:
# size
np.random.normal(size=5)

array([-1.01092541,  0.58092445,  1.122653  , -0.1252049 ,  0.57716007])

In [207]:
l = range(10)
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [209]:
np.random.shuffle(l)
l

[7, 5, 2, 9, 4, 0, 8, 3, 6, 1]